DROP TABLE IF EXISTS `paAddress`;
CREATE TABLE `paAddress` (
  `postcode` VARCHAR(12) NOT NULL,
  `created`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `content`  LONGTEXT    NOT NULL,
  PRIMARY KEY (`postcode`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
